
import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { 
  getSupabaseConfig, setSupabaseConfig, testApiConnection
} from '../services/db';
import { 
  LogOut, Moon, Sun, Check, AlertCircle, 
  CheckCircle, RefreshCw, Globe, ShieldAlert, Play, Server, 
  Database, Copy, Info, Terminal, HardDrive,
  ExternalLink, Lock, Unlock, Database as DbIcon, ShieldCheck,
  Monitor, Settings as SettingsIcon, AlertOctagon, MousePointer2, ChevronRight, Zap,
  AlertTriangle, DatabaseZap
} from 'lucide-react';

const SUPABASE_SQL_SCRIPT = `-- 🚀 Supabase Setup Script for QC Master
CREATE TABLE IF NOT EXISTS products (
    barcode TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    cost_price NUMERIC DEFAULT 0,
    unit_price NUMERIC DEFAULT 0,
    lot_no TEXT,
    product_type TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS qc_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT,
    product_name TEXT,
    cost_price NUMERIC,
    selling_price NUMERIC,
    status TEXT,
    reason TEXT,
    remark TEXT,
    inspector_id TEXT,
    image_urls JSONB DEFAULT '[]'::jsonb,
    lot_no TEXT,
    product_type TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Products" ON products;
CREATE POLICY "Public Access Products" ON products FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access QC Logs" ON qc_logs;
CREATE POLICY "Public Access QC Logs" ON qc_logs FOR ALL TO anon USING (true) WITH CHECK (true);

-- 💡 TIPS: หากคุณสร้างตารางไปแล้ว ให้รันคำสั่งเหล่านี้เพื่อเพิ่มคอลัมน์ที่ขาดหายไป:
-- ALTER TABLE qc_logs ADD COLUMN IF NOT EXISTS lot_no TEXT;
-- ALTER TABLE qc_logs ADD COLUMN IF NOT EXISTS product_type TEXT;`;

export const Settings: React.FC = () => {
  const { logout } = useAuth();
  const { isDark, toggleTheme } = useTheme();
  const initialConfig = getSupabaseConfig();
  const [url, setUrl] = useState(initialConfig.url);
  const [key, setKey] = useState(initialConfig.key);
  
  const [testStatus, setTestStatus] = useState<{status: 'idle' | 'loading' | 'success' | 'error', message: string, code?: string}>({status: 'idle', message: ''});
  const [activeTab, setActiveTab] = useState<'config' | 'sql'>('config');

  const handleSaveConfig = () => {
    setSupabaseConfig(url, key);
    alert('บันทึกการตั้งค่าสำเร็จ');
  };

  const handleTestConnection = async () => {
    setTestStatus({status: 'loading', message: 'Connecting...'});
    const result = await testApiConnection(url, key);
    if (result.success) {
      setTestStatus({status: 'success', message: 'เชื่อมต่อ Cloud สำเร็จ!'});
    } else {
      setTestStatus({status: 'error', message: result.error || 'การเชื่อมต่อล้มเหลว'});
    }
  };

  const copy = (text: string, msg: string) => {
    navigator.clipboard.writeText(text);
    alert(msg);
  };

  return (
    <div className="space-y-6 pb-24 animate-fade-in max-w-5xl mx-auto">
      <div className="flex justify-between items-center px-2">
        <h1 className="text-3xl font-display font-bold text-gray-800 dark: